### ISSUE TITLE
Cannot tap due to iosevka-generate

### ISSUE THREAD

**Issue by 23RoboticRabbits** [OJFord/homebrew-formulae#1]
Tapping this repository now fails with:
```
intermute:scripts mike.roth$ brew tap OJFord/formulae
==> Tapping ojford/formulae
Cloning into '/usr/local/Homebrew/Library/Taps/ojford/homebrew-formulae'...
remote: Counting objects: 8, done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 8 (delta 0), reused 3 (delta 0), pack-reused 0
Unpacking objects: 100% (8/8), done.
Error: Invalid formula: /usr/local/Homebrew/Library/Taps/ojford/homebrew-formulae/iosevka-generate.rb
Unsupported special dependency :otfccbuild
Error: Cannot tap ojford/formulae: invalid syntax in tap!
```

**Comment by strobh** [comment]
Same for me. It seems to be a dependency to [https://github.com/caryll/otfcc](https://github.com/caryll/otfcc). The owner probably installed it and therefore doesn't get this error.

**Comment by fotomut** [comment]
I've been using https://github.com/jgerhold/homebrew-formulae fork for the moment. That change, https://github.com/jgerhold/homebrew-formulae/commit/f62abab3a94d252e628ba7d9c3e8955bd18b1e16, seems to fix the dependency issue.

**Comment by OJFord** [comment]
Apologies for this - and I'm sorry I haven't replied! I seem not to get notifications of issues/PRs to my repos, definitely need to sort that out.

I actually just experienced this myself on a new machine, and I've 'fixed' it temporarily by just removing the dependency in 8d76e89b40a76089ecd6270852ccbe961b7f6cfa.

I have not yet tested iosevka-generate without that dependency though, so beware if installing that tool that you may need to source otfcc manually. I will test that (and find a better solution if it is an issue) when I have the time.

As an aside, it's pretty frustrating that even `brew install OJFord/formulae/whatever` fails due to an error inside a non-`whatever` formula.

**Comment by OJFord** [comment]
Sorry @strobi - I didn't see your PR either (or until after above comment) - thank you for the fix!
